runtime: python37

service: allin-apps-1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /practice/
  static_files: allin-practice/index.html
  upload: allin-practice/index.html
- url: /practice
  secure: always
  redirect_http_response_code: 301
  static_dir: allin-practice

- url: /.*
  secure: always
  script: auto

automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_concurrent_requests: 80
  target_throughput_utilization: 0.8
  max_idle_instances: 1
  min_idle_instances: 0
  min_pending_latency: 10s
  max_pending_latency: 15s
