runtime: python37

service: allin-apps-2

handlers:
- url: /.*
  secure: always
  script: auto

automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_concurrent_requests: 80
  target_throughput_utilization: 0.8
  max_idle_instances: 1
  min_idle_instances: 0
  min_pending_latency: 10s
  max_pending_latency: 15s
